name: continuous-integration-example

on:
  push:
      branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Build with Gradle
        working-directory: .
        run: ./gradlew build -x test
